# Generated by Django 4.2.3 on 2023-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_definition', models.CharField(max_length=200)),
                ('url_link', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('important', models.BooleanField(choices=[(True, 'Important'), (False, 'Average')], verbose_name='Important or Average')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
    ]
