# Generated by Django 4.2.3 on 2023-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url_link',
            field=models.CharField(max_length=250, verbose_name='link'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('url_link',), name='unique_url'),
        ),
    ]
